package com.radojcic.login;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

import com.radojcic.gui.MainConsole;
import com.radojcic.networking.IClientListener;

/**
*
*/
public class LoginWindow extends javax.swing.JFrame implements IClientListener.MessageListener {

	// New chat widnow field
	private LoginListener loginListener;
	private UserDetails ud;

	/**
	 * Creates new form LoginWindow
	 */
	public LoginWindow(LoginListener loginListener) {
		this.loginListener = loginListener;
		initComponents();

		init();

	}

	private void init() {
		setVisible(true);

		addWindowListener(new WindowAdapter() {
			@Override
			public void windowOpened(WindowEvent e) {
				mUserName.requestFocus();
			}
		});
	}

	@Override
	public void onNewMessage(String message) {
		if (message.contains("loginsuccess::")) {
			loginListener.onLoginComplete(ud);
			return;
		}

		SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				mMessageWindow.append(message + "\n");
				JScrollBar vertical = mScrollPane.getVerticalScrollBar();
				vertical.setValue(vertical.getMaximum());
			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		mLogin = new javax.swing.JButton();
		mUserName = new javax.swing.JTextField();
		mLastName = new javax.swing.JTextField();
		mScrollPane = new javax.swing.JScrollPane();
		mMessageWindow = new javax.swing.JTextArea();
		jLabel3 = new javax.swing.JLabel();
		mFirstName = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		mLogin.setText("LOGIN");
		mLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mLoginActionPerformed(evt);
			}
		});

		mUserName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mUserNameActionPerformed(evt);
			}
		});

		mLastName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mLastNameActionPerformed(evt);
			}
		});

		mMessageWindow.setEditable(false);
		mMessageWindow.setColumns(20);
		mMessageWindow.setLineWrap(true);
		mMessageWindow.setRows(3);
		mScrollPane.setViewportView(mMessageWindow);

		jLabel3.setText("Last name");

		mFirstName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mFirstNameActionPerformed(evt);
			}
		});

		jLabel1.setText("Username");

		jLabel2.setText("First name");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(mScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
								.addComponent(mLogin, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1).addGap(18, 18, 18)
										.addComponent(mUserName))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addComponent(jLabel2).addGap(18, 18, 18)
												.addComponent(mFirstName))
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel3).addGap(18, 18, 18)
										.addComponent(mLastName)))
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(mScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(mUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(mFirstName).addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										31, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(mLastName).addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
										31, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18).addComponent(mLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	private void mUserNameActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void mFirstNameActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void mLastNameActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void mLoginActionPerformed(java.awt.event.ActionEvent evt) {
		ud = new UserDetails(mFirstName.getText(), mLastName.getText(), mUserName.getText());
		loginListener.onLogin(ud);
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField mFirstName;
	private javax.swing.JTextField mLastName;
	private javax.swing.JButton mLogin;
	private javax.swing.JTextArea mMessageWindow;
	private javax.swing.JScrollPane mScrollPane;
	private javax.swing.JTextField mUserName;
	// End of variables declaration

	@Override
	public void onNewMessage(byte[] audioMessage) {
		throw new RuntimeException("Method not implemented.");
	}
}
