package com.radojcic.gui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.text.DefaultCaret;

import com.radojcic.networking.IClientListener;
import com.radojcic.networking.IMessageSender;
import com.radojcic.networking.error.ConnectionErrorException;
import com.radojcic.util.Messages;

public class ChatWindow extends JFrame implements IClientListener.MessageReceiverListener {

	  // Variables declaration - do not modify                     
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mNewMsgArea;
    private javax.swing.JTextArea mMessagesWindow;
    private javax.swing.JButton mRecord;
    private javax.swing.JButton mSend;
    private javax.swing.JButton mStop;
    // End of variables declaration      
	
	private IMessageSender msgSender;
	private String chatBuddyName;
	private boolean chatEnded;

	public ChatWindow(IMessageSender msgSender, String chatBuddy) {
		super("Chat room: " + chatBuddy);
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

		this.msgSender = msgSender;
		if (msgSender == null)
			dispose();
		this.chatBuddyName = chatBuddy;

		init();
	}

	/**
	 * Initialise variables
	 */
	private void init() {
		initComponents();		
		setListener();
		setVisible(true);
	}
	
	/**
	 * Set action listeners onto fields
	 */
	private void setListener() {
		mNewMsgArea.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					msgSender.sendMessage(e.getActionCommand());
					mNewMsgArea.setText("");
				} catch (ConnectionErrorException ex) {
					mNewMsgArea.setText("Chat has been disconected.");
					mNewMsgArea.setEditable(false);
				}
			}
		});

		addWindowListener(new WindowAdapter() {
			@Override
			public void windowOpened(WindowEvent e) {
				mNewMsgArea.requestFocus();
			}

			@Override
			public void windowClosed(WindowEvent arg0) {
				if (!chatEnded){
					chatEnded = true;
					try {
						ChatWindow.this.msgSender.sendMessage(Messages.CON_END_REQ);
					} catch (ConnectionErrorException ex) {
						System.out.println("Sending message failed: " + ex.getLocalizedMessage());
					}
				}
				super.windowClosed(arg0);
			}
		});
	}

	@Override
	public void onNewMessage(String message) {
		if (message.startsWith(Messages.CON_END_REQ)) {
			this.chatEnded = true;
			this.dispose();
			return;
		}

		SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				ChatWindow.this.mMessagesWindow.append(message + "\n");
			}
		});
	}
	
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mRecord = new javax.swing.JButton();
        mSend = new javax.swing.JButton();
        mStop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mMessagesWindow = new javax.swing.JTextArea();
        mNewMsgArea = new javax.swing.JTextField();

        mRecord.setText("Snimi");

        mSend.setText("Posalji");

        mStop.setText("Stop");

        mMessagesWindow.setEditable(false);
        mMessagesWindow.setColumns(20);
        mMessagesWindow.setRows(5);
        jScrollPane1.setViewportView(mMessagesWindow);

        mNewMsgArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mNewMsgArea)
                    .addComponent(mSend, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(mRecord, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mStop, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mNewMsgArea, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mStop, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mSend, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                                                                   
}
